### ISSUE TITLE
Stuck at sudo node august-server.js

### ISSUE THREAD

**Issue by kuppurao** [mtvg/August#8]
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
TypeError: path must be a string
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/pi/August/august-server.js:144:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by mtvg** [comment]
Seems like the path to your HTTPS certificate is not correctly set in your `config.js`
If you don't need HTTPS, just comment the line `config.httpsServerPort = 8443;` in the `config.js` file
