### ISSUE TITLE
Hanging when attempting to load the page

### ISSUE THREAD

**Issue by johnnyensign** [mtvg/August#9]
When navigating to http://raspberrypi.local:8080/august/control/status, the page hangs. Lock and Unlock load with { system: "unlocking" } and locking, but it doesn't actually control the lock.

When attempting to curl the url: 

> pi@home:~ $ curl http://localhost/august/control/status
> curl: (52) Empty reply from server

**Comment by johnnyensign** [comment]
> Unhandled rejection Error: Transport endpoint is not connected
>     at L2capBle.onStdoutData (/home/pi/August/node_modules/noble/lib/linux/l2cap-ble.js:95:55)
>     at Socket.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:765:14)
>     at Socket.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:427:10)
>     at emitReadable (_stream_readable.js:423:5)
>     at readableAddChunk (_stream_readable.js:166:9)
>     at Socket.Readable.push (_stream_readable.js:128:10)
>     at Pipe.onread (net.js:529:21)

Connected via the touch screen to AugP8GW4 and now this displays in the console when trying to load any of the pages.

**Comment by johnnyensign** [comment]
Just found that every time that this error pops up (~2 to 3 seconds) the red light on the August flashes. 

I am using the Raspberry Pi 3 Model B

**Comment by teknetia** [comment]
I'm having the same issue trying to get my Rpi3 to communicate with the lock, I am wondering if there has been a change with the way the lock and the app communicate that doesn't work with this project anymore and I'm not experienced enough with BLE to capture more about what is going on.

Don't suppose you had any luck?
